### ISSUE TITLE
This application cannot update another ruleset

### ISSUE THREAD

**Issue by andy840119** [starflash-studios/Osu-ModeManager#1]
![image](https://user-images.githubusercontent.com/9100368/92203301-c2a35300-eebb-11ea-8d1c-409f0c6787e4.png)

Even if i typed another ruleset's url and press `Get latest`, still show tau;s ruleset.

**Comment by andy840119** [comment]
URL only accept end with `/`
Like : 
```
https://github.com/karaoke-dev/karaoke/
```

And this is not working : 
```
https://github.com/karaoke-dev/karaoke
```

**Comment by Neonalig** [comment]
Unfortunately, I'm unable to recreate this issue. Are you able to confirm you were logged in correctly? Did you type in the URL, then press the 'Get Latest' button?
I'm currently working on an overhaul for this entire system, but I'd love to fix this issue if possible. 😄
![yes4](https://user-images.githubusercontent.com/16698604/97096952-6d5b1500-16a6-11eb-8df4-fd6e62e41e40.gif)

**Comment by Neonalig** [comment]
Regex patterns have been changed in the latest version. Hopefully this resolves the issue now. 😄
